[project.scripts]
mathx = "mathx.__main__:main"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "mathx"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["src"]
